theme: minima
title: Cedar's Page
author: Cedar Powers
email: cedarmpowers@gmail.com
description: A small sample of what I get up to! This site is created and maintained by Cedar Powers.
github_username: CedarPowers
linkedin_username: cedarpowers

minima:
  skin: classic
  nav_pages:
    - portfolio.md
    - about.md

