theme: minima
title: Cedar's Page
description: A small sample of what I get up to!

minima:
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/CedarPowers"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/cedarpowers"
  nav_pages:
    - about.md
    - projects.md

